### ISSUE TITLE
closing from viewmodel

### ISSUE THREAD

**Issue by deRightDirection** [FantasticFiasco/mvvm-dialogs#114]
I can open from one viewmodel the dialog.

Now I do have a viewmodel on this dialog as well.
After clicking a certain button on this dialog I would like to close the dialog from the viewmodel which is attached to this dialog.

What is the most neat way to do this?

**Comment by FantasticFiasco** [comment]
Hi!

Am I correct in my understanding that you have a main view-model, and is opening a dialog with a dialog view-model, and wish to close that dialog using a button on that dialog? If this is correct, and the opened dialog is modal, then there is a sample called [Demo.ModalDialog](https://github.com/FantasticFiasco/mvvm-dialogs/tree/master/samples/net-framework/Demo.ModalDialog) which is behaving according to your requirements.

**Comment by rogiardi** [comment]
Hi All,
please take a look at my pending PR, I was experiencing same scenario. You can close your window from inside its ViewModel by setting DialogResult if it is modal, otherwise by calling IDialogService.Close(this).
If you don't know if your window is modal or not and if you always need to set the DialogResult before closing, the Close method's refactoring contained inside my PR can help on it. You don't need to worrying about possible DialogNotFoundException error.. Just call it and chek the boolean result if needed
