### ISSUE TITLE
Supporting for non-Window class.

### ISSUE THREAD

**Issue by wakuflair** [FantasticFiasco/mvvm-dialogs#14]
It seems that mvvm-dialogs only supports standard `Window` or inherited class.
We use telerik wpf controls, in which there's a window-like control named "RadWindow", it's not inherited from `Window` class,  mvvm-dialogs can't handle it.
IMO, mvvm-dialogs should abstract the "window", you just need it to show(RadWindow also has Show/ShowDialog methods).

**Comment by FantasticFiasco** [comment]
I'll take a look at it.

Is it possible for you to provide a simple sample without breaking any licensing issues with Telerik?

**Comment by wakuflair** [comment]
I just created a new repo to show you the code: 
https://github.com/wakuflair/MvvmDialogWithTelerik

**Comment by FantasticFiasco** [comment]
Thanks, I'll have a look at it!

**Comment by FantasticFiasco** [comment]
I've uploaded a NuGet pre-release called [MvvmDialogs 3.0.12-beta](https://www.nuget.org/packages/MvvmDialogs).

In order to support custom windows, you'll have to implement a new interface called `MvvmDialogs.IWindow`. Can you verify that your code is working as expected when targeting this pre-release?

If you have any problems with the implementation of `IWindow`, please take a look at the [demo application](https://github.com/FantasticFiasco/mvvm-dialogs/tree/branches/issue-14/src/NET/Demos/Demo.ModalCustomDialog).

**Comment by wakuflair** [comment]
Awesome! The new version worked very well!
I also updated the [MvvmDialogWithTelerik demo](https://github.com/wakuflair/MvvmDialogWithTelerik/tree/test_MvvmDialogs_3.0.12-beta) source code.
Thank you again!

**Comment by FantasticFiasco** [comment]
I'll prepare the code for an official release, I'll notify you when I've uploaded the NuGet package.

**Comment by FantasticFiasco** [comment]
There is now an official release of _MVVM Dialogs_ on NuGet with version 4.0.0.

Thank you for your feedback, and if you encounter any problems please let me know.
