### ISSUE TITLE
on open

### ISSUE THREAD

**Issue by MannusEtten** [FantasticFiasco/mvvm-dialogs#153]
i have a modal dialog and i want to do some action when the dialog is opened
the action has to start automatically after opening the dialog and not when i click a button on this dialog.

is it possible to make a method OnOpen which I can override or implement in my IModalDialogViewModel

that would be super helpful

**Comment by FantasticFiasco** [comment]
Hi again @MannusEtten!

I don't think you need an `OnOpen` override, you can solve it using a trigger from the view, invoked when the view is loaded. I'm doing that in [one of my samples](https://github.com/FantasticFiasco/mvvm-dialogs/tree/master/samples/net-core/Demo.ActivateNonModalDialog).

You have your view, and in its XAML you write.

```xaml
<i:Interaction.Triggers>
    <i:EventTrigger EventName="Loaded">
        <i:InvokeCommandAction Command="{Binding StartClockCommand}" />
    </i:EventTrigger>
</i:Interaction.Triggers>
```

This code will invoke a command in the view model.

```csharp
public class CurrentTimeDialogViewModel : ViewModelBase
{
    public CurrentTimeDialogViewModel()
    {
        StartClockCommand = new RelayCommand(StartClock);
    }

    public ICommand StartClockCommand { get; }
}
```

This works perfectly, and is also easy to write tests for since it's an ordinary command.

Btw, did you get around to create a small demo application showcasing #152?

**Comment by MannusEtten** [comment]
thanks for the quick reply and indeed neat solution! that i not thought about this...
