### ISSUE TITLE
Assign main window events in dialog

### ISSUE THREAD

**Issue by Niko0pl** [FantasticFiasco/mvvm-dialogs#24]
Hello again,
I would like to ask how to assign events that are raised by my dialog (like OnClosing) to main window's methods?

The particular case I want to solve is to do something in my main window, after closing child window (which is custom MVVM dialog, not just YES/NO).

I was thinking about sending delegate in a dialog constructor, but it does not look like very elegant solution. Is there any better way to do that?

**Comment by FantasticFiasco** [comment]
Hello there again.

Is is a modal or a non-modal dialog you are opening from the main window?

**Comment by Niko0pl** [comment]
It is non-modal.
<sup>But in fact what I want to do is hide mainwindow when child window is open and show it again after child close.</sup>

**Comment by FantasticFiasco** [comment]
That is a pretty unconventional in Windows, I would say. I haven't tried the behavior, with or without MVVM Dialogs.

Communication between windows can be achieved either using events if  the view models have a relationship with each other, otherwise using a message dispatcher like the [messenger in MVVM Light](https://msdn.microsoft.com/en-us/magazine/jj694937.aspx).

**Comment by Niko0pl** [comment]
So, I've decided to pass a `MainWindowViewModel`'s event method as an `Action` in the `Show` method. Then, in the `ChildWindowViewModel`'s constructor I attach it as a `OnClose` Command like: `OnClose = new RelayCommand(x => onRouteEditorClose(this, new CancelEventArgs()));`
Maybe it is not the best, because my constructors looks quite complicated but it works.
