### ISSUE TITLE
Integration with PropertyChanged.Fody

### ISSUE THREAD

**Issue by igitur** [FantasticFiasco/mvvm-dialogs#3]
I have an MVVMLight application and I use `PropertyChanged.Fody`. I'm trying to use this library to display dialogs, but after closing the modal dialog, I get an error: `DialogResult can be set only after Window is created and shown as dialog.`

You can reproduce the problem by checking out your `mvvm-light` branch, and by running
`Install-Package PropertyChanged.Fody -ProjectName DemoApplication` to add Fody to `DemoApplication`.

Clicking any of the 2 buttons on the `Modal dialog` tab, entering some text and clicking OK results in the error.

**Comment by FantasticFiasco** [comment]
I've verified that I can reproduce the issue and will start working on it.

Thank you for reporting the issue.

**Comment by FantasticFiasco** [comment]
I've created a new release, v1.1.4. It has been uploaded to nuget.org and you should be able to use it in your application.

What I've done is to be defensive in MVVM Dialogs, making sure that the dialog result isn't set if it already has been set to the specific value.

But, and there is a but here, I think you _might_ encounter other problems in your application if you incorrectly use MVVM Light in combination with PropertyChanged.Fody. The problem was that a property changed notification was sent twice for the property `DialogResult`. One was sent by MVVM Light by the usage of the `Set` method, the other was weaved in by Fody since PropertyChanged.Fody doesn't support the `Set` method.

This [link](https://github.com/Fody/PropertyChanged/wiki/SupportedToolkits) is stating the supported frameworks, and sure MVVM Light is one of them. But it is stated that the only methods supported are:

- For `GalaSoft.MvvmLight.ObservableObject` the method `RaisePropertyChanged` is supported
- For `GalaSoft.MvvmLight.ViewModelBase` the method `RaisePropertyChanged` is supported

The `Set` method is not supported and is the reason as to why the property changed event is sent twice. I've verified this by investigating the IL code with ILSpy.

You need to question yourself if you need PropertyChanged.Fody at all. If you inherit the MVVM Light view models, why would you need to weave in property changed notifications?
