### ISSUE TITLE
Customizing FolderBrowser, Open, Save, Message  Dialogs

### ISSUE THREAD

**Issue by pdinnissen** [FantasticFiasco/mvvm-dialogs#30]
Would you be open to extending your DialogService to have a FrameworkDialog Factory/Interface that provides which FolderBrowser, Open, Save, MessageBox dialogs get used?

I really like this dialog service, but would like to combine it with [Ookii dialogs](https://www.nuget.org/packages/Ookii.Dialogs/) or other dialogs provided other third parties.

I'm willing to do a pull request if you are open to the idea.

**Comment by pdinnissen** [comment]
I've put together a sample in this [fork](https://github.com/pdinnissen/mvvm-dialogs).

I've updated the FolderBrowser Demo accordingly to use the Ookii dialog.

I'm sorry that I haven't followed the proper committing conventions, I just wanted to quickly get some type of Proof of Concept going.

I haven't touched the MessageBox, but that could be easily added in.  I'm also sure some of the changes I've done could also be improved a bit.

**Comment by FantasticFiasco** [comment]
Hi pdinnissen and welcome to the project!

I would also think that to be a good idea, MVVM Dialogs already support custom dialogs, but it would have to be implemented in a way that doesn't get in the way of the mainstream implementation.

I haven't looked at your fork yet, but will probably get to it in a couple of hours, and I would happily accept pull requests. We can work together on it if you would like. In that case permit me push rights to the fork.

**Comment by pdinnissen** [comment]
I believe I've given you the necessary rights.

I think some bit of collaboration would yield the best result.  I believe my sample doesn't touch the mainstream implementation and is also a non-breaking change.  Everything is under the hood and a few new DialogService constructors for all the new permutations.

**Comment by FantasticFiasco** [comment]
I'm going to create new demo projects that focus on the custom framework dialogs, so I'll be moving the code you've added to the project `Demo.FolderBrowserDialog`. Do you have any pending changes in the demo application that you would like to commit before I begin?

**Comment by pdinnissen** [comment]
No.  That's as far as I got.  A new demo makes sense.

**Comment by FantasticFiasco** [comment]
Do you have VS2017 installed? I would like to convert solution to VS2017, but won't if you are running VS2015.

**Comment by pdinnissen** [comment]
Yes.  15.4.

Sent from my Windows 10 phone

**Comment by FantasticFiasco** [comment]
I've caught a nasty bug and might be out a couple of days, but these are the things I plan to commit before we create the pull request and merge back:

- [ ] Review MVVM Dialog changes
- Custom folder browser dialog
  - [x] Add demo application
  - [ ] Fix tests
- Custom open file dialog
  - [ ] Add demo application
  - [ ] Add tests
- Custom save file dialog
  - [ ] Add demo application
  - [ ] Add tests
- Custom message box
  - [ ] Add demo application
  - [ ] Add tests
- [ ] Update CHANGELOG.md

**Comment by pdinnissen** [comment]
I read that too quickly the first time.  I thought you found a nasty bug in
my recommendation.  Feel better and there's no need to rush this pull
request.

I didn't do the code for custom MessageBox, so that needs to be added as
well.  Let me know if you'd like for me to put that together.

**Comment by FantasticFiasco** [comment]
lol yea that was a poor choice of words, no bugs found in your code!

**Comment by FantasticFiasco** [comment]
I think the code is ready for a pull request now.

Can you squash all commits into a single one with the commit message of my final commit, and then create the pull request?

Thanks for the contribution, it's an important one!

**Comment by pdinnissen** [comment]
I couldn't find the option to squash the commits.  Maybe that only appears
when actually merging?

**Comment by FantasticFiasco** [comment]
I'll lead you through it, but let me start. Until I say so, don't pull or fetch your fork.

**Comment by FantasticFiasco** [comment]
We're ready to get to work. We're doing this because I would like you to get credit for the work you've done.

The first thing for you to do is to reset your history. The git commit history has changed because I've squashed all our commits into a single one.

Run the following commands in a prompt of your choice:

```
git fetch
git reset --hard origin/master
```

The next thing for you to do is to claim the last commit as your own. According to [this question](https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit) you should now run:

```
git rebase -i HEAD~1
```

and when vim is opened you should enter edit mode by pressing the `i` key, navigate to the commit using the arrow keys and change `pick` to `edit`. You then exit the edit mode using `Esc`, and then type `:wq` to write to disk and quit.

You will at this point be able to change the author. Type the following in the command prompt:

```
git commit --amend --author="Author Name <email@address.com>"
```

where you replace the name and e-mail address with the one you've configured git to use.

You are then ready to continue the rebase by running the following command:

```
git rebase --continue
```

When the rebase is done, push your changed history to GitHub by running the following command:

```
git push --force
```

And then you are done! You've claimed responsibility for all the changes on your fork.

If you run into any trouble, please let me know and I will try to help you.

**Comment by pdinnissen** [comment]
great instructions.

I think I've completed them.

I appreciate you wanting to give me credit, but to be honest you did do
most of the work and it's your library.  I'm just happy to have given a
good idea to make it better for other's to use (I'm assuming other's also
hate the default folder browser from Windows as much as I do.)

**Comment by FantasticFiasco** [comment]
A new version is now live on nuget.org
