### ISSUE TITLE
Support all .NET Framework versions?

### ISSUE THREAD

**Issue by FantasticFiasco** [FantasticFiasco/mvvm-dialogs#55]
Investigate whether we should support all framework versions. Lets see how `Newtonsoft.Json` is supporting different versions.

For more on specifically .NET Core 3:
- [Migrating a Sample WPF App to .NET Core 3 (Part 1)](https://devblogs.microsoft.com/dotnet/migrating-a-sample-wpf-app-to-net-core-3-part-1/)
- [Migrating a Sample WPF App to .NET Core 3 (Part 2)](https://devblogs.microsoft.com/dotnet/migrating-a-sample-wpf-app-to-net-core-3-part-2/)

**Comment by virzak** [comment]
As I tried to port my project to .NET Core 3.0, MVVMDialogs was one of the many assemblies that did not target either .NET Core or .NET Standard, which prevented the porting.

**Comment by FantasticFiasco** [comment]
Hi virzak!

Yes, the upcoming .NET Core 3.0 is one of the environments we don't support, but let me see if I can get a grasp of the amount of work required to support it. Do you have any good documentation you can point me towards, helping me on my way?

**Comment by virzak** [comment]
You can get the preview SDK from here:
https://github.com/dotnet/core-sdk

And run `dotnet new wpf` to see what the new project looks like.

You need to make 3 changes:
* Target is netcoreapp3.0 and 
* Add `<UseWPF>true</UseWPF>` 
* Add `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">`

And it should compile right away.

**Comment by virzak** [comment]
And need to wait for [multitargeting](https://github.com/dotnet/core-sdk/issues/88) in order to not produce two versions of the library

**Comment by FantasticFiasco** [comment]
@virzak I've hacked up a pre-release preview of the .NET Core 3.0 support, you can find it [here on nuget.org](https://www.nuget.org/packages/MvvmDialogs/5.3.0-dotnet-core-3-preview-1).

For now I'm satisfied. When .NET Core 3.0 finally ships we'll be able to let MvvmDialogs support it. 

Best of lucks with validating your own application for .NET Core 3.0 support!

**Comment by virzak** [comment]
Amazing!!

**Comment by FantasticFiasco** [comment]
I'm unfortunately on holiday this week and next, but will after that start the work to support .NET Core 3.0. I cant wait to get started

**Comment by FantasticFiasco** [comment]
I've now finally [published a beta1 on NuGet](https://www.nuget.org/packages/MvvmDialogs/6.0.0-beta1). Would it be to asking to much if you where to try it out and determine whether it fits your needs?

**Comment by virzak** [comment]
@FantasticFiasco,

All dialogs in my biggest application that uses this library work right out of the box with the latest beta.

I briefly went through examples and discovered at least one bug. I can make a separate issue with suggestions over the weekend if you'd like. Will briefly mention here though:

The bug I found: in Demo.ActivateNonModalDialog.Core you can only show the time dialog once, because the `dialogViewModel` reference is never reset to null.

https://github.com/FantasticFiasco/mvvm-dialogs/blob/32e785eeff5b5038a77960b7b4b24240feff927a/samples/net-core/Demo.ActivateNonModalDialog/MainWindowViewModel.cs#L35

Recently I replaced SimpleIoc with Microsoft.Extensions.DependencyInjection since it plays better with Polly (Microsoft.Extensions.Http.Polly) and [EF Core](https://github.com/aspnet/EntityFrameworkCore/blob/f7526ec44558b159a3f9d5d5c6e6cf1c480202cb/src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs#L476). In general there seems to be very little activity in mvvmlight repo, which is a shame cause it is awesome.

**Comment by FantasticFiasco** [comment]
> All dialogs in my biggest application that uses this library work right out of the box with the latest beta.

Perfect, then I'll start the process of releasing an official version.

> I can make a separate issue with suggestions over the weekend if you'd like.

I would definitely like that. When creating the new .NET Core samples, I noted that the can-execute function wasn't triggered as it does in .NET Framework. Or I made a mistake when I copied the samples and migrated them to .NET Core. Whatever it is, I am eager for your contribution. Thank you very much for your support!

> Recently I replaced SimpleIoc with Microsoft.Extensions.DependencyInjection since it plays better with Polly (Microsoft.Extensions.Http.Polly) and EF Core.

I'll look into that IoC container. I opted to chose sample dependencies that would be familiar to new WPF developers. I'll look into the popularity of Microsoft.Extensions.DependencyInjection. If it gains traction over SimpleIoc I'll have no problem doing the switch.

**Comment by FantasticFiasco** [comment]
v6.0.0 is now [officially released](https://www.nuget.org/packages/MvvmDialogs/6.0.0). I'll close this issue and if we find any problems we'll open new issues.

**Comment by FantasticFiasco** [comment]
> The bug I found: in Demo.ActivateNonModalDialog.Core you can only show the time dialog once, because the dialogViewModel reference is never reset to null.

I think I've found another bug in the .NET Core samples. The command's can-execute method on some samples is not automatically invoked, as it is using MVVM Light in .NET Framework, but has to be invoked by me.
