### ISSUE TITLE
Edit dialog's owner properties when dialog is opened

### ISSUE THREAD

**Issue by Quadrition** [FantasticFiasco/mvvm-dialogs#65]
**Is your feature request related to a problem? Please describe.**
When I want to open a dialog (Window type with WindowStyle=None or UserControl), and if both dialog and dialog's owner have same background color, it is hard to see where are the edges of dialog.

**Describe the solution you'd like**
I would like to be able to change properties of the dialog's owner when the dialog is shown (for example in the case above I want dialog's owner opacity to be reduced while the dialog is displayed.

**Comment by FantasticFiasco** [comment]
Hi and welcome MvvmDialogs!

This seems to be a reasonable feature request, with a clear goal, even though you are the first developer to request this functionality.

Did you decide on building on your own MVVM dialog framework or take a dependency towards MvvmDialogs? The reason I ask is because it sets a time frame on the request. If you decide to roll your own implementation of a dialog service, I would like to keep this issue open, available for other developers with a similar request.

If you would like to take a dependency towards this framework, I would have to build a beta for you to test, making sure the functionality adheres to you request, before continuing with writing sample applications and tests, making it a officially supported feature.

**Comment by Quadrition** [comment]
Hi! I will stick to my implementation of dialog service for now, but I will probably switch to yours in the future. Thanks for helping!

**Comment by FantasticFiasco** [comment]
This repository has transitioned into a state where it's actively maintained but not actively developed. The README has been updated to reflect this. Thanks for the proposal but unfortunately this won't be implemented.
