### ISSUE TITLE
Show dialog from nested ViewModel

### ISSUE THREAD

**Issue by mysteryx93** [FantasticFiasco/mvvm-dialogs#80]
When I have a single ViewModel behind my WPF View, the dialogs are working fine.

However, if I have a ParentViewModel containing a list of ChildViewModel, and try to use a dialog within the ChildViewModel, I get this exception.

> ViewNotRegisteredException: View model of type 'EmergenceGuardian.Player432hz.ViewModels.PlaylistViewModel' is not present as data context on any registered view.Please register the view by setting DialogServiceViews.IsRegistered="True" in your XAML.

As a separate issue, I find it slightly annoying that by default it's not finding files and I must implement a IDialogTypeLocator when using the standard:
- Views folder containing MainView
- ViewModels folder containing MainViewModel

In this case I already have this

```
private class DialogTypeLocator : MvvmDialogs.DialogTypeLocators.IDialogTypeLocator
{
    public Type Locate(INotifyPropertyChanged viewModel)
    {
        if (viewModel is MainViewModel || viewModel is PlaylistViewModel)
            return typeof(MainView);
        else
            throw new Exception("Dialog type is not defined.");
    }
}
```

**Comment by FantasticFiasco** [comment]
Hi mysteryx93 and welcome!

I think I understand your problem, but would you so kindly create a really small GitHub repo showcasing the issue. That way we reduce the risk of misunderstandings.

Regarding the annoying part, I guess you're set on using the [implicit syntax](https://github.com/FantasticFiasco/mvvm-dialogs/wiki/Modal-and-non%E2%80%90modal-dialogs#implicit-dialog-type-syntax-and-the-dialog-type-locator) and not the [explicit syntaxt](https://github.com/FantasticFiasco/mvvm-dialogs/wiki/Modal-and-non%E2%80%90modal-dialogs#explicit-dialog-type-syntax)? You should have good reasons to do so, and you should be confident that the reasons are more valuable to you than just "it is something I read on Stackoverflow" ;)

If you decide on using the implicit syntax, and your naming of views and view models are following a convention, you can always create a really simple dialog locator that you create once and then never update. You can find a good tutorial of how to write it [here](https://github.com/FantasticFiasco/mvvm-dialogs/wiki/Custom-dialog-type-locators).

Please let me know when you've created the small sample application.

**Comment by mysteryx93** [comment]
[NestedDialog.zip](https://github.com/FantasticFiasco/mvvm-dialogs/files/3701168/NestedDialog.zip)
Here's a reproduction of the issue

**Comment by FantasticFiasco** [comment]
Thanks! I'll have a look at it tonight.

**Comment by FantasticFiasco** [comment]
I've created a GitHub repo [here](https://github.com/FantasticFiasco/mvvm-dialogs-issue-80) with your original code, and added the changes required to fix the problem.

The issue you where experiencing was that you didn't set the attached property `md:DialogServiceViews.IsRegistered="True"` where `ChildViewModel` was bound in the XAML. Without this registration there is no way to resolve the mapping your view model to its visual representation, and can thus not open a dialog with its correct owner.

**Comment by mysteryx93** [comment]
Oh... that's a pretty obscure technicality. It can also get troublesome if I'm binding to the child in several places, or navigating a tree of ViewModels via binding.

Let's say I have InboxViewModel within MainViewModel. I can bind a section of the window to InboxViewModel, and elsewhere, also bind the status bar to display how many messages are in the inbox. In that case, do I need to register the child ViewModel at only one of these 2 places?

**Comment by FantasticFiasco** [comment]
If I was the developer I wouldn't bind the same view model to many views, nor one view to many view models. I would create a view for each view model, and I wouldn't reuse view models.

Lets say we have a mail application like Outlook, and that application could be split into the following areas:

- Master pane - List of received e-mails displayed on the left side of the application
- Details pane - Displaying the currently selected e-mail displayed on the right side of the application
- Status bar - Displaying the number of total and unread e-mails displayed on the bottom of the application

I would create this as three views and three view models, and then compose them in the main window. The fact that both the master pane and the status bar has to know the number of received e-mails does not enforce it to be the same view model. In fact it would introduce coupling, and changes to the view model would increase the risk of introducing bugs in one of two views.

So with this application, if all three view models required opening view models, yes then you would have to register the attached property on each view, i.e. three times because each view defines the boundaries of its corresponding view model. I would like you to rethink your design in the provided example where one view was bound to many view models. Conceptually it is easier to map one view to one view models, but then again, you are probably brighter than me and can keep stuff like that in your head :D

Do I answer your question or only make it worse?

**Comment by mysteryx93** [comment]
Thanks, I'm still learning how to properly structure MVVM applications.

In your example, how do you compose 3 view models into the main window, without having a view model with 3 childs? One way is to create a MainViewModel with ChildViewModel like I did; another way would be to bind 3 sections into the ViewModelLocator, if really there's no code needed whatsoever between the 3 sections.

If I take my specific case, it's a very simple app. MainViewModel contains a list of Playlists, and each Playlist is a ViewModel containing a list of Folders, with commands to add or remove folders. Selecting a Playlist on the left then displays the associated ViewModel on the right.

Am I doing it the right way or is there a better way?

**Comment by FantasticFiasco** [comment]
I think a general problem for developers designing WPF applications is that they tend to think to much on the WPF part :D

Something that you will pick up along the way is that WPF doesn't enforce you to structure your application in a specific way. In fact, what your application is defined by is the core logic defining a domain solving one or a multitude of use cases. It has nothing to do with UI at all. A pattern that helped me a lot is the [hexagonal architecture](https://blog.ndepend.com/hexagonal-architecture/) (I just picked the first article that came up in the search). It helped me understand that I needed to define the core of the application, the specific code that describes the domain. It does not involve any UI at all, and I think this is the core of the problem for many WPF developers. WPF is not a core concern, it is just one way to define a UI to the user. You should design your code in a way that makes it possible to replace the WPF UI with another type of UI, e.g. a REST API or a console application.

> another way would be to bind 3 sections into the ViewModelLocator, if really there's no code needed whatsoever between the 3 sections

I think we are ready to answer this question now. Different views will most certainly deal with the same type of data, but this doesn't mean that there should be dependencies between the view models, it means that the view modes probably depend on the common core logic, i.e. class names that are suffixed with `Service` or `Repository` or whatever you like, because if the UI is meant to be replaceable, the logic of your domain cant reside within your view models. I haven't looked at [Prism](http://prismlibrary.github.io/docs/) for a very long time, and I don't urge you to use it, but by reading its documentation you will understand some of the common problems a WPF developer face, and that will get you half of the way. Understanding the problem is probably more important than understanding the solution.

Other than that I would search GitHub for WPF reference applications, and read their code. I hope this is somewhat helpful, but cannot give you a definite answer to your solution. There are many ways to design your application, and all of them are fine. Just write your application and don't think to much. Along the way you will see what works and what doesn't. Experience is king :P

**Comment by mysteryx93** [comment]
The actual work of the application is done in separate components that are injected into the ViewModels.

All the ViewModel is doing is exposing the properties and commands needed to bind the interface, which is very simple code. Holding a list of playlists, holding a list of folders, with 2 commands in each. I don't see how I could make it any simpler.

Even there, in order to have a master-child relationship on the form where you view the details of the selected object (would be the same with hovering over a file to see the file details), there needs to be several ViewModels in the form IF the child objects need custom properties and commands. If not, then binding straight to a Model would work. But even in the case of showing file details, you'd want to do a little bit of coding to customize the appearance, such as changing displaying file size "1000" as "1kb", which would make a simple ViewModel useful.

Anything I'm missing?

**Comment by FantasticFiasco** [comment]
It seems that you are doing just fine :D The master/details relationship could be arranged in the main window, where the selected item in the master pane was bound to the details pane. Or you would create a service that holds the selected item, that the master pane updates when the selection changes and the details pane registers for changes to the selected item. Either way you are solving the problem using levels of indirection.

> If not, then binding straight to a Model would work.

It could, but then your models would have to implement `INotifyPropertyChanged` to be WPF friendly. That would mean leaking UI concepts to your core logic. It wouldn't be prohibited, nothing is, but you should be able to argue to someone that it is the correct thing to do.

I think you have it all covered. I wish you the best of luck in your future endevours!.

**Comment by FantasticFiasco** [comment]
I would abstract it in the view models. Most often the service has a method called `GetItems()` or similar that I would call from the view model, as well as an event called `ItemsChanged` that I would register to when the view model was created.

**Comment by mysteryx93** [comment]
Another option would be to have a generic "SelectableList" with the list of typed objects, SelectedIndex and SelectedItem. Actually I kind of like that option.

Thanks for your insights.
