### ISSUE TITLE
Add support for hosted in winforms

### ISSUE THREAD

**Issue by sknauer-ndt** [FantasticFiasco/mvvm-dialogs#96]
**Is your feature request related to a problem? Please describe.**
Given a winforms form, that has an `ElementHost` with a `Child` set to a wpf `UIElement`.
So there is no real wpf Window, just the ElementHost holding the wpf control.
When attempting to show a dialog somewhere inside the wpf control, the DialogService cannot find the owner window of the ownerViewModel and throws an exception
https://github.com/FantasticFiasco/mvvm-dialogs/blob/59a356e3e35b280a5147f0ff9281ed1f11289c30/src/net/DialogService.cs#L322
while trying to set the owner:
https://github.com/FantasticFiasco/mvvm-dialogs/blob/59a356e3e35b280a5147f0ff9281ed1f11289c30/src/net/DialogService.cs#L279
 

**Describe the solution you'd like**
When a window of the ownerViewModel cannot be found,
search for a winform e.g. with this extension method:
```
public static Form FindForm(this Visual element)
        {
            HwndSource wpfHandle = PresentationSource.FromVisual(element) as HwndSource;

            if (wpfHandle == null)
            {
                return null;
            }

            ElementHost elementHost = System.Windows.Forms.Control.FromChildHandle(wpfHandle.Handle) as ElementHost;
            return elementHost.FindForm();
        }
```
Having that form, one can now set the owner of the WindowWrapper.window:
```
var helper = new WindowInteropHelper(window);
helper.Owner = ownerForm.Handle;
```

**Comment by FantasticFiasco** [comment]
Hi!

Would you be able to provide me with a very small solution where this issue is demonstrated? I can then use that sample to assess whether it is feasible to support your scenario. Mixed WPF and WinForms application is not something I've aimed to support.

**Comment by sknauer-ndt** [comment]
hi, thanks for your quick reply.

here is a small sample (dotnet 4):
https://github.com/sknauer-ndt/supportWpf

There are two projects in this solution:
1. `WpfSample,` which opens MessageBox through MVVMDialogs. This works as expected 
1. `WfHostWpfDialog` which hosts (ElementHost: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.elementhost?view=netframework-4.8) the `UserControl1ViewModel` (https://github.com/sknauer-ndt/supportWpf/blob/master/WpfSample/UserControl1ViewModel.cs) from `WpfSample`. This does not work and causes the exception mentioned above, because `DialogService` isnt able to get the owner-window of `InnerControlViewModel` (https://github.com/sknauer-ndt/supportWpf/blob/master/WpfSample/InnerControlViewModel.cs), because there is no (wpf) Window.

As mentioned above, one might be able to set the owner of the dialog to the handle of the WinForms Form (here: Form1 https://github.com/sknauer-ndt/supportWpf/blob/master/WfHostWpfDialog/Form1.cs)

**Comment by FantasticFiasco** [comment]
Sorry for taking this long, but I really had to think this one through. The short answer is that I don't plan to support WinForms.

The reasoning behind the decision is this. When it comes to new functionality one always have to compare the value of the feature to its cost. Lets start with the value of supporting mixed WPF/WinForms applications. For an application like yours its probably valuable, otherwise you wouldn't have written this issue. But even for you I would argue that the value decreases with time, given that you continuously migrate away from WinForms. But perhaps since you haven't completed the migration, and the introduction of WPF is a distant memory, perhaps your application is stuck in this mixed reality. If so I feel sorry for you. I did spend three years supporting and extending an application that was built on a mix of WinForms and WPF, and management never understood the negative impact that had on the continuous development of the application, and the frustration it presented to the developers. Mixed applications introduce new kind of problems, like the one you've encountered here, but also once that initially seem minor, for instance that you now have two focused elements, one in WPF and one in WinForms. The lack of interest from management to invest into a full migration to WPF was one of many reasons as to why I left that job.

Sorry, but you had me remembering old scars... Back to the estimate of value.

Again, for you this feature would be valuable. But I would argue that I lack the data to come to the conclusion that this is valuable to other developers as well. You are the first one to ask for this. It doesn't mean that there hasn't been other developers that wanted this feature. It just means that I don't know how many they are, and can thus not produce an estimate of the value.

Estimating the cost is far more simple for me. You've already presented a solution, and it seems like a good one to me, thus the implementation will present no cost. However, writing the tests and the sample applications will cost. All aspects of the functionality that is tested using unit and UI tests will also have to be written for WinForms. All the samples written for WPF will also have to be written for WinForms. So a rough estimate would be that I need to double the test and sample suite. That is no small task. Nor is it a task that I find interesting, so it would take considerable longer to finish than an interesting tasks. There is even a risk that I wouldn't complete it, that priorities shifts me into abandoning the task.

I'm really sorry to have to tell you that this isn't something I plan to do. Being open source, you always have the option to fork my implementation and suit it to your needs.

Whatever road you decide to choose, best of wishes, and happy coding!

**Comment by sknauer-ndt** [comment]
Please change e-mail address to

s.knauer@ibgndt.de<mailto:s.knauer@ibgndt.de>

Tnx

Von: Mattias Kindborg @FantasticFiasco [mailto:notifications@github.com]
Gesendet: Mittwoch, 15. Januar 2020 23:12
An: FantasticFiasco/mvvm-dialogs <mvvm-dialogs@noreply.github.com>
Cc: sknauer-ndt <sebastian.knauer@ibgndt.de>; Author <author@noreply.github.com>
Betreff: Re: [FantasticFiasco/mvvm-dialogs] Add support for hosted in winforms (#96)


Sorry for taking this long, but I really had to think this one through. The short answer is that I don't plan to support WinForms.

The reasoning behind the decision is this. When it comes to new functionality one always have to compare the value of the feature to its cost. Lets start with the value of supporting mixed WPF/WinForms applications. For an application like yours its probably valuable, otherwise you wouldn't have written this issue. But even for you I would argue that the value decreases with time, given that you continuously migrate away from WinForms. But perhaps since you haven't completed the migration, and the introduction of WPF is a distant memory, perhaps your application is stuck in this mixed reality. If so I feel sorry for you. I did spend three years supporting and extending an application that was built on a mix of WinForms and WPF, and management never understood the negative impact that had on the continuous development of the application, and the frustration it presented to the developers. Mixed applications introduce new kind of problems, like the one you've encountered here, but also once that initially seem minor, for instance that you now have two focused elements, one in WPF and one in WinForms. The lack of interest from management to invest into a full migration to WPF was one of many reasons as to why I left that job.

Sorry, but you had me remembering old scars... Back to the estimate of value.

Again, for you this feature would be valuable. But I would argue that I lack the data to come to the conclusion that this is valuable to other developers as well. You are the first one to ask for this. It doesn't mean that there hasn't been other developers that wanted this feature. It just means that I don't know how many they are, and can thus not produce an estimate of the value.

Estimating the cost is far more simple for me. You've already presented a solution, and it seems like a good one to me, thus the implementation will present no cost. However, writing the tests and the sample applications will cost. All aspects of the functionality that is tested using unit and UI tests will also have to be written for WinForms. All the samples written for WPF will also have to be written for WinForms. So a rough estimate would be that I need to double the test and sample suite. That is no small task. Nor is it a task that I find interesting, so it would take considerable longer to finish than an interesting tasks. There is even a risk that I wouldn't complete it, that priorities shifts me into abandoning the task.

I'm really sorry to have to tell you that this isn't something I plan to do. Being open source, you always have the option to fork my implementation and suit it to your needs.

Whatever road you decide to choose, best of wishes, and happy coding!

**Comment by sknauer-ndt** [comment]
That's a justifiable decision.
The problem was solved, by dropping this library, but adapting the concept und creating the view manually and propagating the dialogResult from the viewmodel manually.
The ViewModel and the view could still be used at is, there were just changes about 20 lines to be made.
Nevertheless, thanks for your attention

**Comment by FantasticFiasco** [comment]
Well that sounds like the perfect solution. A dependency, even to MVVM Dialogs 😀, comes with a cost. If you are able to solve your problem without this dependency, we are both better off.

**Comment by sknauer-ndt** [comment]
Please delete: sebastian.knauer@ibgndt.de<mailto:sebastian.knauer@ibgndt.de>

Correct address: s.knauer@ibgndt.de<mailto:s.knauer@ibgndt.de>

Tnx.

Von: Mattias Kindborg @FantasticFiasco [mailto:notifications@github.com]
Gesendet: Donnerstag, 16. Januar 2020 09:14
An: FantasticFiasco/mvvm-dialogs <mvvm-dialogs@noreply.github.com>
Cc: sknauer-ndt <sebastian.knauer@ibgndt.de>; Author <author@noreply.github.com>
Betreff: Re: [FantasticFiasco/mvvm-dialogs] Add support for hosted in winforms (#96)


Well that sounds like the perfect solution. A dependency, even to MVVM Dialogs 😀, comes with a cost. If you are able to solve your problem without this dependency, we are both better off.
